# ============================================================
# MAPA DE ABREVIACIONES (ID → Nombre largo)
# ============================================================

BOOK_MAP = {
    "1ch": {"normal": "1 Crónicas", "long": "1 Crónicas", "abbrev": "1 Crón"},
    "1co": {"normal": "1 Corintios", "long": "1 Corintios", "abbrev": "1 Cori"},
    "1jn": {"normal": "1 Juan", "long": "1 Juan", "abbrev": "1 Juan"},
    "1ki": {"normal": "1 Reyes", "long": "1 Reyes", "abbrev": "1 Reye"},
    "1pe": {"normal": "1 Pedro", "long": "1 Pedro", "abbrev": "1 Pedr"},
    "1sa": {"normal": "1 Samuel", "long": "1 Samuel", "abbrev": "1 Samu"},
    "1th": {
        "normal": "1 Tesalonicenses",
        "long": "1 Tesalonicenses",
        "abbrev": "1 Tesa",
    },
    "1ti": {"normal": "1 Timoteo", "long": "1 Timoteo", "abbrev": "1 Timo"},
    "2ch": {"normal": "2 Crónicas", "long": "2 Crónicas", "abbrev": "2 Crón"},
    "2co": {"normal": "2 Corintios", "long": "2 Corintios", "abbrev": "2 Cori"},
    "2jn": {"normal": "2 Juan", "long": "2 Juan", "abbrev": "2 Juan"},
    "2ki": {"normal": "2 Reyes", "long": "2 Reyes", "abbrev": "2 Reye"},
    "2pe": {"normal": "2 Pedro", "long": "2 Pedro", "abbrev": "2 Pedr"},
    "2sa": {"normal": "2 Samuel", "long": "2 Samuel", "abbrev": "2 Samu"},
    "2th": {
        "normal": "2 Tesalonicenses",
        "long": "2 Tesalonicenses",
        "abbrev": "2 Tesa",
    },
    "2ti": {"normal": "2 Timoteo", "long": "2 Timoteo", "abbrev": "2 Timo"},
    "3jn": {"normal": "3 Juan", "long": "3 Juan", "abbrev": "3 Juan"},
    "act": {"normal": "Hechos", "long": "Hechos", "abbrev": "Hechos"},
    "amo": {"normal": "Amós", "long": "Amós", "abbrev": "Amós"},
    "col": {"normal": "Colosenses", "long": "Colosenses", "abbrev": "Colose"},
    "dan": {"normal": "Daniel", "long": "Daniel", "abbrev": "Daniel"},
    "deu": {"normal": "Deuteronomio", "long": "Deuteronomio", "abbrev": "Deuter"},
    "ecc": {"normal": "Eclesiastés", "long": "Eclesiastés", "abbrev": "Eclesi"},
    "eph": {"normal": "Efesios", "long": "Efesios", "abbrev": "Efesio"},
    "est": {"normal": "Ester", "long": "Ester", "abbrev": "Ester"},
    "exo": {"normal": "Éxodo", "long": "Éxodo", "abbrev": "Éxodo"},
    "ezk": {"normal": "Ezequiel", "long": "Ezequiel", "abbrev": "Ezequi"},
    "ezr": {"normal": "Esdras", "long": "Esdras", "abbrev": "Esdras"},
    "gal": {"normal": "Gálatas", "long": "Gálatas", "abbrev": "Gálata"},
    "gen": {"normal": "Génesis", "long": "Génesis", "abbrev": "Génesi"},
    "hab": {"normal": "Habacuc", "long": "Habacuc", "abbrev": "Habacu"},
    "hag": {"normal": "Hageo", "long": "Hageo", "abbrev": "Hageo"},
    "heb": {"normal": "Hebreos", "long": "Hebreos", "abbrev": "Hebreo"},
    "hos": {"normal": "Oseas", "long": "Oseas", "abbrev": "Oseas"},
    "isa": {"normal": "Isaías", "long": "Isaías", "abbrev": "Isaías"},
    "jas": {"normal": "Santiago", "long": "Santiago", "abbrev": "Santia"},
    "jdg": {"normal": "Jueces", "long": "Jueces", "abbrev": "Jueces"},
    "jer": {"normal": "Jeremías", "long": "Jeremías", "abbrev": "Jeremí"},
    "jhn": {"normal": "Juan", "long": "Juan", "abbrev": "Juan"},
    "job": {"normal": "Job", "long": "Job", "abbrev": "Job"},
    "jol": {"normal": "Joel", "long": "Joel", "abbrev": "Joel"},
    "jon": {"normal": "Jonás", "long": "Jonás", "abbrev": "Jonás"},
    "jos": {"normal": "Josué", "long": "Josué", "abbrev": "Josué"},
    "jud": {"normal": "Judas", "long": "Judas", "abbrev": "Judas"},
    "lam": {"normal": "Lamentaciones", "long": "Lamentaciones", "abbrev": "Lament"},
    "lev": {"normal": "Levítico", "long": "Levítico", "abbrev": "Levíti"},
    "luk": {"normal": "Lucas", "long": "Lucas", "abbrev": "Lucas"},
    "mal": {"normal": "Malaquías", "long": "Malaquías", "abbrev": "Malaqu"},
    "mat": {"normal": "Mateo", "long": "Mateo", "abbrev": "Mateo"},
    "mic": {"normal": "Miqueas", "long": "Miqueas", "abbrev": "Miquea"},
    "mrk": {"normal": "Marcos", "long": "Marcos", "abbrev": "Marcos"},
    "nam": {"normal": "Nahum", "long": "Nahum", "abbrev": "Nahum"},
    "neh": {"normal": "Nehemías", "long": "Nehemías", "abbrev": "Nehemí"},
    "num": {"normal": "Números", "long": "Números", "abbrev": "Número"},
    "oba": {"normal": "Abdías", "long": "Abdías", "abbrev": "Abdías"},
    "phm": {"normal": "Filemón", "long": "Filemón", "abbrev": "Filemó"},
    "php": {"normal": "Filipenses", "long": "Filipenses", "abbrev": "Filipe"},
    "pro": {"normal": "Proverbios", "long": "Proverbios", "abbrev": "Prover"},
    "psa": {"normal": "Salmos", "long": "Salmos", "abbrev": "Salmos"},
    "rev": {"normal": "Apocalipsis", "long": "Apocalipsis", "abbrev": "Apocal"},
    "rom": {"normal": "Romanos", "long": "Romanos", "abbrev": "Romano"},
    "rut": {"normal": "Rut", "long": "Rut", "abbrev": "Rut"},
    "sng": {"normal": "Cantares", "long": "Cantar de los Cantares", "abbrev": "Cantar"},
    "tit": {"normal": "Tito", "long": "Tito", "abbrev": "Tito"},
    "zec": {"normal": "Zacarías", "long": "Zacarías", "abbrev": "Zacarí"},
    "zep": {"normal": "Sofonías", "long": "Sofonías", "abbrev": "Sofoní"},
}

# ============================================================
# MAPA DE ABREVIACIONES (USFM → Nombre)
# ============================================================

USFM_TO_NAME = {
    "GEN": "Génesis",
    "EXO": "Éxodo",
    "LEV": "Levítico",
    "NUM": "Números",
    "DEU": "Deuteronomio",
    "JOS": "Josué",
    "JDG": "Jueces",
    "RUT": "Rut",
    "1SA": "1 Samuel",
    "2SA": "2 Samuel",
    "1KI": "1 Reyes",
    "2KI": "2 Reyes",
    "1CH": "1 Crónicas",
    "2CH": "2 Crónicas",
    "EZR": "Esdras",
    "NEH": "Nehemías",
    "EST": "Ester",
    "JOB": "Job",
    "PSA": "Salmos",
    "PRO": "Proverbios",
    "ECC": "Eclesiastés",
    "SNG": "Cantares",
    "ISA": "Isaías",
    "JER": "Jeremías",
    "LAM": "Lamentaciones",
    "EZK": "Ezequiel",
    "DAN": "Daniel",
    "HOS": "Oseas",
    "JOL": "Joel",
    "AMO": "Amós",
    "OBA": "Abdías",
    "JON": "Jonás",
    "MIC": "Miqueas",
    "NAM": "Nahum",
    "HAB": "Habacuc",
    "ZEP": "Sofonías",
    "HAG": "Hageo",
    "ZEC": "Zacarías",
    "MAL": "Malaquías",
    "MAT": "Mateo",
    "MRK": "Marcos",
    "LUK": "Lucas",
    "JHN": "Juan",
    "ACT": "Hechos",
    "ROM": "Romanos",
    "1CO": "1 Corintios",
    "2CO": "2 Corintios",
    "GAL": "Gálatas",
    "EPH": "Efesios",
    "PHP": "Filipenses",
    "COL": "Colosenses",
    "1TH": "1 Tesalonicenses",
    "2TH": "2 Tesalonicenses",
    "1TI": "1 Timoteo",
    "2TI": "2 Timoteo",
    "TIT": "Tito",
    "PHM": "Filemón",
    "HEB": "Hebreos",
    "JAS": "Santiago",
    "1PE": "1 Pedro",
    "2PE": "2 Pedro",
    "1JN": "1 Juan",
    "2JN": "2 Juan",
    "3JN": "3 Juan",
    "JUD": "Judas",
    "REV": "Apocalipsis",
}
